{{- if .Values.configMaps.enabled }}
{{- range .Values.configMaps.configMapDetails }}
{{- if .enabled }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .name }}
  labels:
    helm-chart/release-name: {{ $.Release.Name }}
    helm.sh/chart: '{{ $.Chart.Name }}-{{ $.Chart.Version | replace "+" "_" }}'
    {{- range $key, $value := $.Values.commonLables }}
    {{ $key }}: {{ $value | quote }}
    {{- end }} 
  annotations:
    helm-chart/release-version: {{ $.Chart.Version | replace "+" "_" }}
    {{- range $key, $value := $.Values.commonAnnotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }} 
data:
  {{- if eq .type "string" }}
  {{ .fileName }}: |
    {{- tpl .data $ | nindent 4 }}
  {{- else if eq .type "keyValues" }}
  {{- range $key, $value := .data }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
  {{- end }}
{{- end }}
{{- end }}
{{- end }}
