{{- if .Values.secrets.enabled }}
{{- range $key, $val := .Values.secrets.secretDetails }}
{{- if .enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .name }}
  labels:
    helm-chart/release-name: {{ $.Release.Name }}
    helm.sh/chart: '{{ $.Chart.Name }}-{{ $.Chart.Version | replace "+" "_" }}'
    {{- range $key, $value := $.Values.commonLables }}
    {{ $key }}: {{ $value | quote }}
    {{- end }} 
  annotations:
    helm-chart/release-version: {{ $.Chart.Version | replace "+" "_" }}
    {{- range $key, $value := $.Values.commonAnnotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }} 
type: {{ .secretType }}
data:
  {{- if eq .type "string" }}
  {{ .fileName }}: {{ $encodedData := .data | indent 4 | b64enc }}{{ $encodedData | quote }}
  {{- else if eq .type "keyValues" }}
  {{- range $key, $value := .data }}
  {{ $key }}: {{ $value | quote | b64enc }}
  {{- end }}
  {{- end }}
{{- end }}
{{- end }}
{{- end }}
