{{- range $key, $val := .Values.secrets }}
{{- if .enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .name }}
type: {{ .secretType }}
data:
  {{- if eq .type "string" }}
  {{ .fileName }}: |
    {{- .data | b64enc | quote | nindent 4 -}}
  {{- else if eq .type "keyValues" }}
  {{- range $key, $value := .data }}
  {{ $key }}: {{ $value | quote | b64enc }}
  {{- end }}
  {{- end }}
{{- end }}
{{- end }}
---