{{- range $key, $val := .Values.secrets }}
{{- if .enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .name }}
  labels:
    {{- range $key, $value := $.Values.commonLables }}
    {{ $key }}: {{ $value | quote }}
    {{- end }} 
  annotations:
    {{- range $key, $value := $.Values.commonAnnotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }} 
type: {{ .secretType }}
data:
  {{- if eq .type "string" }}
  {{ .fileName }}: |
    {{- .data | quote | b64enc | nindent 4 }}
  {{- else if eq .type "keyValues" }}
  {{- range $key, $value := .data }}
  {{ $key }}: {{ $value | quote | b64enc }}
  {{- end }}
  {{- end }}
{{- end }}
{{- end }}
---