---
# Source: configMapSecrets/templates/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: app-properties
type: Opaque
data:
  db.string: |
    "c29tZSBmaWxlIGNvbnRlbnQKd2l0aCBkZXRhaWxzIG9mIHRoZSBhcHBsaWNhdGlvbgo="
---
# Source: configMapSecrets/templates/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: env-details
type: Opaque
data:
  ENV: ImRldmVsb3Ai
  HOST: ImxvY2FsaG9zdCI=
  PORT: IjgwODAi
