---
# Source: configMapSecrets/templates/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: app-properties
  labels:
    helm-chart/release-name: demo
    helm.sh/chart: 'configMapSecrets-0.0.12'
    this-is-a-label: "some label" 
  annotations:
    helm-chart/release-version: 0.0.12
    this-is-an-annotaion: "some annotation" 
type: Opaque
data:
  dbstring: "ICAgIHNvbWUgZmlsZSBjb250ZW50CiAgICB3aXRoIGRldGFpbHMgb2YgdGhlIGFwcGxpY2F0aW9uCiAgICA="
---
# Source: configMapSecrets/templates/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: env-details
  labels:
    helm-chart/release-name: demo
    helm.sh/chart: 'configMapSecrets-0.0.12'
    this-is-a-label: "some label" 
  annotations:
    helm-chart/release-version: 0.0.12
    this-is-an-annotaion: "some annotation" 
type: Opaque
data:
  ENV: ImRldmVsb3Ai
  HOST: ImxvY2FsaG9zdCI=
  PORT: IjgwODAi
